Test setFailed

diff --git a/.github/workflows/pytest_and_ruff.yml b/.github/workflows/pytest_and_ruff.yml
--- a/.github/workflows/pytest_and_ruff.yml
+++ b/.github/workflows/pytest_and_ruff.yml
@@ -88,5 +88,8 @@ jobs:
       run: echo "MERGE_VERSION=$(python setup.py --version)" >> $GITHUB_ENV
     - name: A/B Check
       if: ${{ env.MERGE_VERSION == env.MAIN_VERSION }}
-      run: echo "::error Version unchanged from main=${MAIN_VERSION}" && exit 1
+      uses: actions/github-script@v3
+      with:
+        script: core.setFailed('Version unchanged from main=${MAIN_VERSION}!')
+      # run: echo "::error Version unchanged from main=${MAIN_VERSION}" && exit 1
         # exit 1
